# Guna image rasmi Tomcat + Java
FROM tomcat:9.0-jdk11

# Padam default aplikasi ROOT Tomcat (optional)
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Salin WAR ke folder webapps
COPY HomestayFinder.war /usr/local/tomcat/webapps/HomestayFinder.war

# Buka port default Tomcat
EXPOSE 8080
